from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

from .audit import audit_curriculum
from .checks import CourseCheckError, check_lesson


ROOT = Path(__file__).resolve().parents[2]
CURRICULUM_PATH = ROOT / "course" / "curriculum.json"
PROGRESS_MARKER = re.compile(
    r"<!-- SIGNALDESK_PROGRESS\n(?P<payload>.*?)\n-->",
    re.DOTALL,
)


class CourseError(RuntimeError):
    """Raised for a learner-facing curriculum error."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_curriculum() -> dict[str, Any]:
    if not CURRICULUM_PATH.is_file():
        raise CourseError(f"missing curriculum: {CURRICULUM_PATH}")
    curriculum = json.loads(CURRICULUM_PATH.read_text(encoding="utf-8"))
    lessons = curriculum.get("lessons")
    if not isinstance(lessons, list) or not lessons:
        raise CourseError("curriculum does not contain lessons")
    return curriculum


def progress_path() -> Path:
    configured = os.environ.get("SIGNALDESK_LEARNING_FILE")
    return Path(configured).expanduser().resolve() if configured else ROOT / "LEARNING.md"


def empty_progress() -> dict[str, Any]:
    return {
        "schema_version": 1,
        "started_at": utc_now(),
        "updated_at": utc_now(),
        "lessons": {},
    }


def load_progress(path: Path | None = None) -> dict[str, Any]:
    path = path or progress_path()
    if not path.exists():
        return empty_progress()
    match = PROGRESS_MARKER.search(path.read_text(encoding="utf-8"))
    if not match:
        raise CourseError(
            f"{path} exists but does not contain SignalDesk progress metadata"
        )
    progress = json.loads(match.group("payload"))
    if progress.get("schema_version") != 1:
        raise CourseError("unsupported learner progress schema")
    return progress


def save_progress(
    curriculum: dict[str, Any],
    progress: dict[str, Any],
    path: Path | None = None,
) -> Path:
    path = path or progress_path()
    progress["updated_at"] = utc_now()
    rows = []
    complete = 0
    available = 0
    for lesson in curriculum["lessons"]:
        if lesson["status"] != "available":
            continue
        available += 1
        state = progress["lessons"].get(lesson["id"], {})
        status = state.get("status", "not_started")
        complete += status == "complete"
        rows.append(f"| {lesson['id']} | {lesson['title']} | {status} |")

    payload = json.dumps(progress, indent=2, sort_keys=True)
    body = "\n".join(
        [
            "# SignalDesk Learning Progress",
            "",
            "> Generated by `python run_course.py`. Keep this file for your own",
            "> learning record; it is intentionally ignored by Git.",
            "",
            "<!-- SIGNALDESK_PROGRESS",
            payload,
            "-->",
            "",
            "## Progress",
            "",
            f"Available pilot lessons completed: **{complete}/{available}**",
            "",
            "| Lesson | Title | Status |",
            "|---|---|---|",
            *rows,
            "",
            "## Reflection rule",
            "",
            "A technical check verifies repository evidence. A lesson is complete only",
            "after you record, in your own words, what decision the evidence supports.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


def lesson_by_id(curriculum: dict[str, Any], lesson_id: str) -> dict[str, Any]:
    lesson_id = lesson_id.zfill(2)
    for lesson in curriculum["lessons"]:
        if lesson["id"] == lesson_id:
            return lesson
    raise CourseError(f"unknown lesson: {lesson_id}")


def require_available(lesson: dict[str, Any]) -> None:
    if lesson["status"] != "available" or not lesson.get("lesson_path"):
        raise CourseError(
            f"lesson {lesson['id']} is planned but not available in the pilot"
        )


def command_doctor(_: argparse.Namespace) -> int:
    curriculum = load_curriculum()
    core_checks = {
        "Python 3.11+": sys.version_info >= (3, 11),
        "Git executable": shutil.which("git") is not None,
        "Curriculum manifest": CURRICULUM_PATH.is_file(),
        "Six pilot lessons": sum(
            lesson["status"] == "available" for lesson in curriculum["lessons"]
        )
        == 6,
    }
    for lesson in curriculum["lessons"]:
        if lesson["status"] == "available":
            core_checks[f"Lesson {lesson['id']} guide"] = (
                ROOT / lesson["lesson_path"]
            ).is_file()

    optional = {
        "pytest (verification labs)": importlib.util.find_spec("pytest") is not None,
        "duckdb (warehouse labs)": importlib.util.find_spec("duckdb") is not None,
        "numpy (data labs)": importlib.util.find_spec("numpy") is not None,
        "faker (data labs)": importlib.util.find_spec("faker") is not None,
        "pyarrow (Parquet data labs)": importlib.util.find_spec("pyarrow") is not None,
        "OpenAI key (optional live labs)": bool(os.environ.get("OPENAI_API_KEY")),
    }
    print("SignalDesk course doctor\n")
    for label, passed in core_checks.items():
        print(f"[{'ok' if passed else 'missing'}] {label}")
    print("\nOptional capabilities")
    for label, passed in optional.items():
        print(f"[{'ok' if passed else 'not configured'}] {label}")
    print("\nFrozen course checks make no model API calls.")
    return 0 if all(core_checks.values()) else 1


def command_list(_: argparse.Namespace) -> int:
    curriculum = load_curriculum()
    progress = load_progress()
    print("ID  STATUS       PROGRESS       MIN  TITLE")
    for lesson in curriculum["lessons"]:
        state = progress["lessons"].get(lesson["id"], {})
        learner_status = state.get("status", "not_started")
        print(
            f"{lesson['id']}  {lesson['status']:<12} "
            f"{learner_status:<14} {lesson['estimated_minutes']:>3}  "
            f"{lesson['title']}"
        )
    return 0


def command_audit(_: argparse.Namespace) -> int:
    curriculum = load_curriculum()
    errors = audit_curriculum(ROOT, curriculum)
    if errors:
        print("Course audit failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    available = sum(
        lesson["status"] == "available" for lesson in curriculum["lessons"]
    )
    print(
        f"Course audit passed: {len(curriculum['lessons'])} mapped lessons, "
        f"{available} available pilot lessons."
    )
    return 0


def command_start(args: argparse.Namespace) -> int:
    curriculum = load_curriculum()
    lesson = lesson_by_id(curriculum, args.lesson_id)
    require_available(lesson)
    progress = load_progress()
    state = progress["lessons"].setdefault(lesson["id"], {})
    state.setdefault("started_at", utc_now())
    state["status"] = "in_progress"

    incomplete = [
        prerequisite
        for prerequisite in lesson["prerequisites"]
        if progress["lessons"].get(prerequisite, {}).get("status") != "complete"
    ]
    path = save_progress(curriculum, progress)
    print(f"Lesson {lesson['id']}: {lesson['title']}")
    print(f"Guide: {ROOT / lesson['lesson_path']}")
    print(f"Estimated time: {lesson['estimated_minutes']} minutes")
    if incomplete:
        print(f"Recommended prerequisites not complete: {', '.join(incomplete)}")
    print(f"Progress: {path}")
    print(f"\nWhen ready: python run_course.py check {lesson['id']}")
    return 0


def command_check(args: argparse.Namespace) -> int:
    curriculum = load_curriculum()
    lesson = lesson_by_id(curriculum, args.lesson_id)
    require_available(lesson)
    checked = check_lesson(ROOT, lesson["id"])
    print(f"Frozen evidence check passed for lesson {lesson['id']}:")
    for artifact in checked:
        print(f"- {artifact}")

    verification_args = lesson.get("verification_args", [])
    if verification_args:
        command = [sys.executable, *verification_args]
        print(f"\nRunning local verification: {' '.join(command)}")
        sys.stdout.flush()
        result = subprocess.run(command, cwd=ROOT, check=False)
        if result.returncode != 0:
            raise CourseError(
                f"lesson {lesson['id']} verification exited {result.returncode}"
            )

    progress = load_progress()
    state = progress["lessons"].setdefault(lesson["id"], {})
    state.setdefault("started_at", utc_now())
    state["status"] = "in_progress"
    state["verified_at"] = utc_now()
    save_progress(curriculum, progress)
    print("\nTechnical checkpoint verified with zero model calls.")
    print(
        "Record your explanation with: "
        f"python run_course.py complete {lesson['id']} --reflection \"...\""
    )
    return 0


def command_complete(args: argparse.Namespace) -> int:
    curriculum = load_curriculum()
    lesson = lesson_by_id(curriculum, args.lesson_id)
    require_available(lesson)
    reflection = args.reflection.strip()
    if len(reflection) < 20:
        raise CourseError("reflection must contain at least 20 characters")
    progress = load_progress()
    state = progress["lessons"].get(lesson["id"], {})
    if not state.get("verified_at"):
        raise CourseError(
            f"run `python run_course.py check {lesson['id']}` before completion"
        )
    state["status"] = "complete"
    state["completed_at"] = utc_now()
    state["reflection"] = reflection
    progress["lessons"][lesson["id"]] = state
    path = save_progress(curriculum, progress)
    print(f"Completed lesson {lesson['id']}: {lesson['title']}")
    print(f"Progress: {path}")
    return 0


def command_next(_: argparse.Namespace) -> int:
    curriculum = load_curriculum()
    progress = load_progress()
    available = [
        lesson for lesson in curriculum["lessons"] if lesson["status"] == "available"
    ]
    for lesson in available:
        if progress["lessons"].get(lesson["id"], {}).get("status") != "complete":
            print(f"Next lesson: {lesson['id']} - {lesson['title']}")
            print(f"Start: python run_course.py start {lesson['id']}")
            return 0
    print("All available pilot lessons are complete.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Navigate and verify the SignalDesk Learning Edition."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    doctor = subparsers.add_parser("doctor", help="check the local learning setup")
    doctor.set_defaults(handler=command_doctor)

    list_command = subparsers.add_parser("list", help="list the 18-lesson map")
    list_command.set_defaults(handler=command_list)

    audit = subparsers.add_parser("audit", help="validate curriculum structure and links")
    audit.set_defaults(handler=command_audit)

    start = subparsers.add_parser("start", help="start an available lesson")
    start.add_argument("lesson_id")
    start.set_defaults(handler=command_start)

    check = subparsers.add_parser("check", help="verify frozen lesson evidence")
    check.add_argument("lesson_id")
    check.set_defaults(handler=command_check)

    complete = subparsers.add_parser(
        "complete", help="complete a verified lesson with a reflection"
    )
    complete.add_argument("lesson_id")
    complete.add_argument("--reflection", required=True)
    complete.set_defaults(handler=command_complete)

    next_command = subparsers.add_parser("next", help="show the next pilot lesson")
    next_command.set_defaults(handler=command_next)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.handler(args))
    except (CourseCheckError, CourseError, json.JSONDecodeError) as exc:
        print(f"course error: {exc}", file=sys.stderr)
        return 1
